name: Execute Ansible Playbook

on:
  push:
    branches:
      - main

jobs:
  ansible_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Ansible
        run: pip install ansible
      - name: install pipcop
        run: pip install psycopg2-binary
      - name: Run Ansible playbook
        run: ansible-playbook -e "ansible_python_interpreter=/usr/bin/python2" playbook.yaml
